### ISSUE TITLE
[Error] WordViewModel has no zero argument constructor

### ISSUE THREAD

**Issue by dhirajhimani** [googlecodelabs/android-room-with-a-view#130]
Caused by: java.lang.RuntimeException: Cannot create an instance of class com.example.android.roomwordssample.WordViewModel
        at androidx.lifecycle.ViewModelProvider$NewInstanceFactory.create(ViewModelProvider.java:221)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:187)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
        at com.example.android.roomwordssample.MainActivity.onCreate(MainActivity.kt:45)
        at android.app.Activity.performCreate(Activity.java:6975)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6541) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
     Caused by: java.lang.InstantiationException: java.lang.Class<com.example.android.roomwordssample.WordViewModel> has no zero argument constructor

getting this error for clean build install

**Comment by klyinin** [comment]
try: 
private lateinit var wordViewModel: WordViewModel
val factory = ViewModelProvider.AndroidViewModelFactory.getInstance(application)
wordViewModel = ViewModelProvider(this,factory).get(WordViewModel::class.java)

**Comment by dhirajhimani** [comment]
Thanks, @klyinin yes you are right we can use the AndroidViewModelFactory, or we can use ViewModelProvider.Factory too create the viewmodel. 
I did the same in https://github.com/googlecodelabs/android-room-with-a-view/pull/133/files

**Comment by sainifacundo-tech** [comment]
I added this line to gradle and it worked:

implementation "androidx.activity: activity: 1.1.0"

**Comment by florina-muntenescu** [comment]
Issue not applicable. The codelab was refactored meanwhile.
