### ISSUE TITLE
Cannot create an instance of class com.example.roomwordsample.WordViewModel

### ISSUE THREAD

**Issue by sahianmol1** [googlecodelabs/android-room-with-a-view#143]
It seems like the project is not able to create WordViewModel object.

Here's the error as per logical:  Process: com.example.roomwordsample, PID: 8721
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.roomwordsample/com.example.roomwordsample.MainActivity}: java.lang.RuntimeException: Cannot create an instance of class com.example.roomwordsample.WordViewModel
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.RuntimeException: Cannot create an instance of class com.example.roomwordsample.WordViewModel
        at androidx.lifecycle.ViewModelProvider$NewInstanceFactory.create(ViewModelProvider.java:221)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:187)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
        at com.example.roomwordsample.MainActivity.onCreate(MainActivity.java:25)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
     Caused by: java.lang.InstantiationException: java.lang.Class<com.example.roomwordsample.WordViewModel> has no zero argument constructor
        at java.lang.Class.newInstance(Native Method)
        at androidx.lifecycle.ViewModelProvider$NewInstanceFactory.create(ViewModelProvider.java:219)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:187) 
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150) 
        at com.example.roomwordsample.MainActivity.onCreate(MainActivity.java:25) 
        at android.app.Activity.performCreate(Activity.java:7802) 
        at android.app.Activity.performCreate(Activity.java:7791) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by MIGMLG** [comment]
> Was facing the same issue. Try this when getting a ViewModel from the ViewModelProvider:
> `mWordViewModel = new ViewModelProvider(this, new ViewModelProvider.AndroidViewModelFactory(getApplication())).get(WordViewModel.class);`
> Hope it helps!

Thank you so much XD. They should update the code with this.

**Comment by dc4e** [comment]
> Was facing the same issue. Try this when getting a ViewModel from the ViewModelProvider:
> `mWordViewModel = new ViewModelProvider(this, new ViewModelProvider.AndroidViewModelFactory(getApplication())).get(WordViewModel.class);`
> Hope it helps!

Thank you for saving my day :D

**Comment by serag24** [comment]
> Was facing the same issue. Try this when getting a ViewModel from the ViewModelProvider: `mWordViewModel = new ViewModelProvider(this, new ViewModelProvider.AndroidViewModelFactory(getApplication())).get(WordViewModel.class);` Hope it helps!

Hello. I am trying to instantiate a viewModel based on a viewModelFactory, and I keep getting the same issue. Can you help me?

//Code for the factory:
public class AddPersonViewModelFactory extends ViewModelProvider.NewInstanceFactory {

private final AppDatabase mDb;
private final int mPersonId;

public AddPersonViewModelFactory(AppDatabase database, int personId) {
    mDb = database;
    mPersonId = personId;
}

    @NotNull
    @Override
    public <T extends ViewModel> T create(@NotNull Class<T> modelClass) {
        //noinspection unchecked
        return (T) new AddPersonViewModel(mDb, mPersonId);
    }
}

//Code for the viewModel:
public class AddPersonViewModel extends ViewModel {

    private final LiveData<PersonEntry> person;

    public AddPersonViewModel(AppDatabase database, int personId) {
        person = database.personDao().loadPersonById(personId);
    }

    public LiveData<PersonEntry> getPerson() {
        return person;
    }
}

//Code in onCreate, AddPersonActivity:
AddPersonViewModelFactory viewModelFactory = new AddPersonViewModelFactory(mDb, mPersonId);
AddPersonViewModel viewModel = new ViewModelProvider(this, viewModelFactory).get(AddPersonViewModel.class);

**Comment by morarafrank** [comment]
Getting the same error when instantiating the repository in the viewmodel constructor. what could be the issue?

**Comment by morarafrank** [comment]
as in class NewsArticlesViewModel( private val repository: NewsRepository): ViewModel(){}...
