### ISSUE TITLE
Application cannot be cast to.. 

### ISSUE THREAD

**Issue by LucaM24** [googlecodelabs/android-room-with-a-view#156]
Hello everybody,
i went through this turotial twice and i think i got everything right
the thing is that i changed it up a little bit to add a column to the table to fit it into my situation to build an transactionsapp. 
is someone facing the same problem? it doesnt seem to occur because of the changes i made because a friend of mine is trying to do it too and went through the tutorial withouth changing something and he is getting the same problem.

2021-01-28 14:42:26.318 10478-10478/com.example.finanzenroom E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.finanzenroom, PID: 10478
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.finanzenroom/com.example.finanzenroom.MainActivity}: java.lang.ClassCastException: android.app.Application cannot be cast to com.example.finanzenroom.TransactionApplication
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.ClassCastException: android.app.Application cannot be cast to com.example.finanzenroom.TransactionApplication
        at com.example.finanzenroom.MainActivity$transactionViewModel$2.invoke(MainActivity.kt:17)
        at com.example.finanzenroom.MainActivity$transactionViewModel$2.invoke(MainActivity.kt:14)
        at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:52)
        at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:41)
        at com.example.finanzenroom.MainActivity.getTransactionViewModel(Unknown Source:2)
        at com.example.finanzenroom.MainActivity.onCreate(MainActivity.kt:28)
        at android.app.Activity.performCreate(Activity.java:8000)
        at android.app.Activity.performCreate(Activity.java:7984)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by matale** [comment]
Its difficult to help without seeing code. But I suspect something is wrong with your TransactionApplication class or you have not added it to the AndroidManifest.xml in the name attribute like  line 6 here [AndroidManifest.xml](https://github.com/googlecodelabs/android-room-with-a-view/blob/kotlin/app/src/main/AndroidManifest.xml)

**Comment by florina-muntenescu** [comment]
> android.app.Application cannot be cast to com.example.finanzenroom.TransactionApplication

The codelab already adds `WordsApplication`. Did you create another one? Did you update the AndroidManifest?

Closing this as this is not an issue with the codelab, but rather with something done outside it.

**Comment by JonasDD0102** [comment]
> É difícil ajudar sem ver o código. Mas é suspeito que algo esteja errado com sua classe TransactionApplication ou você não adicionou ao AndroidManifest.xml no atributo name como a linha 6 aqui [AndroidManifest.xml](https://github.com/googlecodelabs/android-room-with-a-view/blob/kotlin/app/src/main/AndroidManifest.xml)

muito obrigado amigo sua dica me ajudou muito.
