### ISSUE TITLE
 WordRoomDatabase_Impl does not exist

### ISSUE THREAD

**Issue by Prateek447** [googlecodelabs/android-room-with-a-view#176]
.MainActivity}: java.lang.RuntimeException: cannot find implementation for com.example..RoomDB.WordRoomDatabase. WordRoomDatabase_Impl does not exist
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3175)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3312)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:113)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:71)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2038)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:226)
        at android.app.ActivityThread.main(ActivityThread.java:7178)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:503)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
     Caused by: java.lang.RuntimeException: cannot find implementation for com.example.mycodebook.roomsampleapp.RoomDB.WordRoomDatabase. WordRoomDatabase_Impl does not exist
        at androidx.room.Room.getGeneratedImplementation(Room.java:97)
        at androidx.room.RoomDatabase$Builder.build(RoomDatabase.java:1358)
        at com.example.mycodebook.roomsampleapp.RoomDB.WordRoomDatabase$Companion.getDatabase(WordRoomDatabase.kt:44)
        at com.example.mycodebook.roomsampleapp.WordsApplication$database$2.invoke(WordsApplication.kt:31)
        at com.example.mycodebook.roomsampleapp.WordsApplication$database$2.invoke(WordsApplication.kt:25)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.example.mycodebook.roomsampleapp.WordsApplication.getDatabase(Unknown Source:2)
        at com.example.mycodebook.roomsampleapp.WordsApplication$repository$2.invoke(WordsApplication.kt:32)
        at com.example.mycodebook.roomsampleapp.WordsApplication$repository$2.invoke(WordsApplication.kt:25)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.example.mycodebook.roomsampleapp.WordsApplication.getRepository(Unknown Source:2)
        at com.example.mycodebook.roomsampleapp.MainActivity$wordViewModel$2.invoke(MainActivity.kt:22)
        at com.example.mycodebook.roomsampleapp.MainActivity$wordViewModel$2.invoke(MainActivity.kt:18)
        at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:52)
        at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:41)
        at com.example.mycodebook.roomsampleapp.MainActivity.getWordViewModel(Unknown Source:2)
        at com.example.mycodebook.roomsampleapp.MainActivity.onCreate(MainActivity.kt:37)
        at android.app.Activity.performCreate(Activity.java:7383)
        at android.app.Activity.performCreate(Activity.java:7374)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3155)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3312) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:113) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:71) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2038) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:226) 
        at android.app.ActivityThread.main(ActivityThread.java:7178) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:503) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)

**Comment by januprasad** [comment]
+1 Why these idiots not updating this code @google

**Comment by florina-muntenescu** [comment]
`WordRoomDatabase_Impl` is generated at compile time by Room.
Try cleaning the app and building it again.
