### ISSUE TITLE
I am  trying  to   create  an  instance  of   my database  view model

### ISSUE THREAD

**Issue by afsalmuhammed97** [googlecodelabs/android-room-with-a-view#201]
Process: com.practies.musicapp, PID: 3260
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.practies.musicapp/com.practies.musicapp.PlayScreenActivity}: java.lang.RuntimeException: Cannot create an instance of class com.practies.musicapp.view_model.MusicViewModel
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3319)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415)
        at android.app.ActivityThread.-wrap17(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:7325)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
     Caused by: java.lang.RuntimeException: Cannot create an instance of class com.practies.musicapp.view_model.MusicViewModel
        at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:236)
        at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.java:112)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:169)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:139)
        at com.practies.musicapp.PlayScreenActivity.onCreate(PlayScreenActivity.kt:69)
        at android.app.Activity.performCreate(Activity.java:6904)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3266)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415) 
        at android.app.ActivityThread.-wrap17(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:7325) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
     Caused by: java.lang.reflect.InvocationTargetException
        at

>

**Comment by afsalmuhammed97** [comment]
I  got  an  error   ,when   I    create   an   istense  of   my   database  view model   in   one   of  my   activity ,  in    onCreate (  )   I   tryied     this ,
 musicViewModel= ViewModelProvider(this )[MusicViewModel::class.java] 
 to   get   access  to  my   room  database    can  any one   solve  this?
